const UTILS_PARAMS_UNIQUE_PROP = "artist_name";
const UTILS_PARAMS_SLICE_LIMIT = 30;
const UTILS_PARAMS_SEPARETOR = ", ";

const ARGS_TEMPLATE = "from # artists";
const ARGS_REPLACER = "#";

export {
  UTILS_PARAMS_UNIQUE_PROP,
  UTILS_PARAMS_SLICE_LIMIT,
  UTILS_PARAMS_SEPARETOR,
  ARGS_TEMPLATE,
  ARGS_REPLACER
};
