const appActions = {
  REQUEST_PLAYLISTS_DATA: "REQUEST_PLAYLISTS_DATA",
  REQUEST_PLAYLISTS_DATA_SUCCESS: "REQUEST_PLAYLISTS_DATA_SUCCESS",
  REQUEST_PLAYLISTS_DATA_ERROR: "REQUEST_PLAYLISTS_DATA_ERROR",
  RETRIEVE_SERIALIZED_STATE: "RETRIEVE_SERIALIZED_STATE",
};

export { appActions };
